export default [
  {
    _id: "123",
    username: "alice",
    password: "alice123",
    firstName: "Alice",
    lastName: "Wonderland",
    role: "FACULTY",
    email: "alice@wonderland.com",
    dob: "1962-07-17",
  },
  {
    _id: "234",
    username: "bob",
    password: "bob123",
    firstName: "Bob",
    lastName: "Marley",
    role: "STUDENT",
    email: "bob@marley.com",
    dob: "1962-02-18",
  },
  {
    _id: "345",
    username: "charlie",
    password: "charlie123",
    firstName: "Charlie",
    lastName: "Brown",
    role: "FACULTY",
    email: "charlie@brown.com",
    dob: "1976-03-07",
  },
  {
    _id: "456",
    username: "dan",
    password: "dan123",
    firstName: "Dan",
    lastName: "Craig",
    role: "STUDENT",
    email: "dan@craig.com",
    dob: "1981-03-02",
  },
  {
    _id: "567",
    username: "ed",
    password: "ed123",
    firstName: "Ed",
    lastName: "Sheeran",
    role: "FACULTY",
    email: "ed@sheeran.com",
    dob: "1991-02-17",
  },
]; 